### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by aqureshimy** [uzairakbar/HetNet-performance-analysis#1]
Dear Uzair, Thank you for sharing your work on GitHub. Is there any Publication associated with this so as to enable us to understand the work in more depth (needless to say, integrity of the documentation would be highly respected and it would be properly cited / referred)

**Comment by uzairakbar** [comment]
@aqureshimy 
Yes, we have submitted our initial results to [IWCMC 2017](http://iwcmc.org/2017/) (Spain), which have been accepted for publication. You can view the archived version at https://arxiv.org/abs/1705.04390 .

We are also working on some new results regarding 3D channel modeling, a multi-slope path-loss model and resource optimization in HetNets. I will share the latest results here once the manuscript is ready and has been accepted for publication.
